### PR TITLE
Move nuts down

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/3DprintFIT/B171HW-Assignment/issues/11

### CODE REVIEW

**Comment by syky27** [comment]
There is not an image from below, showing how the nut is imprinted into the model...

**Review by syky27 — CHANGES_REQUESTED** [review]
Incorporate image that shows the nut holes on the bottom of the model...

**Comment by hroncok** [comment]
assets/tablet_bottom.png

**Comment by syky27** [comment]
Oh my bad...

**Review by syky27 — APPROVED** [review]

**Comment by hroncok** [comment]
See also 0524a3470256d7c25a94f52d9242a42fd703c310

**Comment by syky27** [comment]
i did

**Pull request merged**
